import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ApiProvider } from "./context/ApiContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ReID Web Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <ApiProvider>{children}</ApiProvider>
      </body>
    </html>
  );
}
